/* AutoGenerated Code, changes may be overwritten
* INPUT GRAMMAR:
* line := t={ linecomment | instruction } $
* linecomment := lc='[*;].*'
* instruction := s={ws? | codeline} sc=comment?
* ws := skip='\s+'
* comment := ';.*'
* codeline := l=label? c=content?
* label := i=identifier c=':'?
* identifier := '@?[a-zA-Z_][a-zA-Z0-9_]*'
* content := { opcode | directive }
* opcode := unimplemented
* directive := d={title | include | unimplemented}
* title := ws? dir='.title'i ws args=nqstring ws?
* include := ws? dir='.include'i ws args=nqstring ws?
* nqstring := nq={qstring | words}
* qstring := '"' v='[^"]*' '"'
* words := w={!'"' !'\s' '.*\S'}
* unimplemented := '##################################'
*/
type Nullable<T> = T | null;
type $$RuleType<T> = () => Nullable<T>;
export interface ASTNodeIntf {
    kind: ASTKinds;
}
export enum ASTKinds {
    line = "line",
    line_$0_1 = "line_$0_1",
    line_$0_2 = "line_$0_2",
    linecomment = "linecomment",
    instruction = "instruction",
    instruction_$0_1 = "instruction_$0_1",
    instruction_$0_2 = "instruction_$0_2",
    ws = "ws",
    comment = "comment",
    codeline = "codeline",
    label = "label",
    identifier = "identifier",
    content = "content",
    content_$0_1 = "content_$0_1",
    content_$0_2 = "content_$0_2",
    opcode = "opcode",
    directive = "directive",
    directive_$0_1 = "directive_$0_1",
    directive_$0_2 = "directive_$0_2",
    directive_$0_3 = "directive_$0_3",
    title = "title",
    include = "include",
    nqstring = "nqstring",
    nqstring_$0_1 = "nqstring_$0_1",
    nqstring_$0_2 = "nqstring_$0_2",
    qstring = "qstring",
    words = "words",
    words_$0 = "words_$0",
    unimplemented = "unimplemented",
    $EOF = "$EOF",
}
export interface line {
    kind: ASTKinds.line;
    t: line_$0;
}
export type line_$0 = line_$0_1 | line_$0_2;
export type line_$0_1 = linecomment;
export type line_$0_2 = instruction;
export interface linecomment {
    kind: ASTKinds.linecomment;
    lc: string;
}
export interface instruction {
    kind: ASTKinds.instruction;
    s: instruction_$0;
    sc: Nullable<comment>;
}
export type instruction_$0 = instruction_$0_1 | instruction_$0_2;
export type instruction_$0_1 = Nullable<ws>;
export type instruction_$0_2 = codeline;
export interface ws {
    kind: ASTKinds.ws;
    skip: string;
}
export type comment = string;
export interface codeline {
    kind: ASTKinds.codeline;
    l: Nullable<label>;
    c: Nullable<content>;
}
export interface label {
    kind: ASTKinds.label;
    i: identifier;
    c: Nullable<string>;
}
export type identifier = string;
export type content = content_$0;
export type content_$0 = content_$0_1 | content_$0_2;
export type content_$0_1 = opcode;
export type content_$0_2 = directive;
export type opcode = unimplemented;
export interface directive {
    kind: ASTKinds.directive;
    d: directive_$0;
}
export type directive_$0 = directive_$0_1 | directive_$0_2 | directive_$0_3;
export type directive_$0_1 = title;
export type directive_$0_2 = include;
export type directive_$0_3 = unimplemented;
export interface title {
    kind: ASTKinds.title;
    dir: string;
    args: nqstring;
}
export interface include {
    kind: ASTKinds.include;
    dir: string;
    args: nqstring;
}
export interface nqstring {
    kind: ASTKinds.nqstring;
    nq: nqstring_$0;
}
export type nqstring_$0 = nqstring_$0_1 | nqstring_$0_2;
export type nqstring_$0_1 = qstring;
export type nqstring_$0_2 = words;
export interface qstring {
    kind: ASTKinds.qstring;
    v: string;
}
export interface words {
    kind: ASTKinds.words;
    w: words_$0;
}
export interface words_$0 {
    kind: ASTKinds.words_$0;
}
export type unimplemented = string;
export class Parser {
    private readonly input: string;
    private pos: PosInfo;
    private negating: boolean = false;
    private memoSafe: boolean = true;
    constructor(input: string) {
        this.pos = {overallPos: 0, line: 1, offset: 0};
        this.input = input;
    }
    public reset(pos: PosInfo): void {
        this.pos = pos;
    }
    public finished(): boolean {
        return this.pos.overallPos === this.input.length;
    }
    public clearMemos(): void {
    }
    public matchline($$dpth: number, $$cr?: ErrorTracker): Nullable<line> {
        return this.run<line>($$dpth,
            () => {
                let $scope$t: Nullable<line_$0>;
                let $$res: Nullable<line> = null;
                if (true
                    && ($scope$t = this.matchline_$0($$dpth + 1, $$cr)) !== null
                    && this.match$EOF($$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.line, t: $scope$t};
                }
                return $$res;
            });
    }
    public matchline_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<line_$0> {
        return this.choice<line_$0>([
            () => this.matchline_$0_1($$dpth + 1, $$cr),
            () => this.matchline_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchline_$0_1($$dpth: number, $$cr?: ErrorTracker): Nullable<line_$0_1> {
        return this.matchlinecomment($$dpth + 1, $$cr);
    }
    public matchline_$0_2($$dpth: number, $$cr?: ErrorTracker): Nullable<line_$0_2> {
        return this.matchinstruction($$dpth + 1, $$cr);
    }
    public matchlinecomment($$dpth: number, $$cr?: ErrorTracker): Nullable<linecomment> {
        return this.run<linecomment>($$dpth,
            () => {
                let $scope$lc: Nullable<string>;
                let $$res: Nullable<linecomment> = null;
                if (true
                    && ($scope$lc = this.regexAccept(String.raw`(?:[*;].*)`, "", $$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.linecomment, lc: $scope$lc};
                }
                return $$res;
            });
    }
    public matchinstruction($$dpth: number, $$cr?: ErrorTracker): Nullable<instruction> {
        return this.run<instruction>($$dpth,
            () => {
                let $scope$s: Nullable<instruction_$0>;
                let $scope$sc: Nullable<Nullable<comment>>;
                let $$res: Nullable<instruction> = null;
                if (true
                    && ($scope$s = this.matchinstruction_$0($$dpth + 1, $$cr)) !== null
                    && (($scope$sc = this.matchcomment($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.instruction, s: $scope$s, sc: $scope$sc};
                }
                return $$res;
            });
    }
    public matchinstruction_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<instruction_$0> {
        return this.choice<instruction_$0>([
            () => this.matchinstruction_$0_1($$dpth + 1, $$cr),
            () => this.matchinstruction_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchinstruction_$0_1($$dpth: number, $$cr?: ErrorTracker): Nullable<instruction_$0_1> {
        return this.matchws($$dpth + 1, $$cr);
    }
    public matchinstruction_$0_2($$dpth: number, $$cr?: ErrorTracker): Nullable<instruction_$0_2> {
        return this.matchcodeline($$dpth + 1, $$cr);
    }
    public matchws($$dpth: number, $$cr?: ErrorTracker): Nullable<ws> {
        return this.run<ws>($$dpth,
            () => {
                let $scope$skip: Nullable<string>;
                let $$res: Nullable<ws> = null;
                if (true
                    && ($scope$skip = this.regexAccept(String.raw`(?:\s+)`, "", $$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.ws, skip: $scope$skip};
                }
                return $$res;
            });
    }
    public matchcomment($$dpth: number, $$cr?: ErrorTracker): Nullable<comment> {
        return this.regexAccept(String.raw`(?:;.*)`, "", $$dpth + 1, $$cr);
    }
    public matchcodeline($$dpth: number, $$cr?: ErrorTracker): Nullable<codeline> {
        return this.run<codeline>($$dpth,
            () => {
                let $scope$l: Nullable<Nullable<label>>;
                let $scope$c: Nullable<Nullable<content>>;
                let $$res: Nullable<codeline> = null;
                if (true
                    && (($scope$l = this.matchlabel($$dpth + 1, $$cr)) || true)
                    && (($scope$c = this.matchcontent($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.codeline, l: $scope$l, c: $scope$c};
                }
                return $$res;
            });
    }
    public matchlabel($$dpth: number, $$cr?: ErrorTracker): Nullable<label> {
        return this.run<label>($$dpth,
            () => {
                let $scope$i: Nullable<identifier>;
                let $scope$c: Nullable<Nullable<string>>;
                let $$res: Nullable<label> = null;
                if (true
                    && ($scope$i = this.matchidentifier($$dpth + 1, $$cr)) !== null
                    && (($scope$c = this.regexAccept(String.raw`(?::)`, "", $$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.label, i: $scope$i, c: $scope$c};
                }
                return $$res;
            });
    }
    public matchidentifier($$dpth: number, $$cr?: ErrorTracker): Nullable<identifier> {
        return this.regexAccept(String.raw`(?:@?[a-zA-Z_][a-zA-Z0-9_]*)`, "", $$dpth + 1, $$cr);
    }
    public matchcontent($$dpth: number, $$cr?: ErrorTracker): Nullable<content> {
        return this.matchcontent_$0($$dpth + 1, $$cr);
    }
    public matchcontent_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<content_$0> {
        return this.choice<content_$0>([
            () => this.matchcontent_$0_1($$dpth + 1, $$cr),
            () => this.matchcontent_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchcontent_$0_1($$dpth: number, $$cr?: ErrorTracker): Nullable<content_$0_1> {
        return this.matchopcode($$dpth + 1, $$cr);
    }
    public matchcontent_$0_2($$dpth: number, $$cr?: ErrorTracker): Nullable<content_$0_2> {
        return this.matchdirective($$dpth + 1, $$cr);
    }
    public matchopcode($$dpth: number, $$cr?: ErrorTracker): Nullable<opcode> {
        return this.matchunimplemented($$dpth + 1, $$cr);
    }
    public matchdirective($$dpth: number, $$cr?: ErrorTracker): Nullable<directive> {
        return this.run<directive>($$dpth,
            () => {
                let $scope$d: Nullable<directive_$0>;
                let $$res: Nullable<directive> = null;
                if (true
                    && ($scope$d = this.matchdirective_$0($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.directive, d: $scope$d};
                }
                return $$res;
            });
    }
    public matchdirective_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<directive_$0> {
        return this.choice<directive_$0>([
            () => this.matchdirective_$0_1($$dpth + 1, $$cr),
            () => this.matchdirective_$0_2($$dpth + 1, $$cr),
            () => this.matchdirective_$0_3($$dpth + 1, $$cr),
        ]);
    }
    public matchdirective_$0_1($$dpth: number, $$cr?: ErrorTracker): Nullable<directive_$0_1> {
        return this.matchtitle($$dpth + 1, $$cr);
    }
    public matchdirective_$0_2($$dpth: number, $$cr?: ErrorTracker): Nullable<directive_$0_2> {
        return this.matchinclude($$dpth + 1, $$cr);
    }
    public matchdirective_$0_3($$dpth: number, $$cr?: ErrorTracker): Nullable<directive_$0_3> {
        return this.matchunimplemented($$dpth + 1, $$cr);
    }
    public matchtitle($$dpth: number, $$cr?: ErrorTracker): Nullable<title> {
        return this.run<title>($$dpth,
            () => {
                let $scope$dir: Nullable<string>;
                let $scope$args: Nullable<nqstring>;
                let $$res: Nullable<title> = null;
                if (true
                    && ((this.matchws($$dpth + 1, $$cr)) || true)
                    && ($scope$dir = this.regexAccept(String.raw`(?:.title)`, "i", $$dpth + 1, $$cr)) !== null
                    && this.matchws($$dpth + 1, $$cr) !== null
                    && ($scope$args = this.matchnqstring($$dpth + 1, $$cr)) !== null
                    && ((this.matchws($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.title, dir: $scope$dir, args: $scope$args};
                }
                return $$res;
            });
    }
    public matchinclude($$dpth: number, $$cr?: ErrorTracker): Nullable<include> {
        return this.run<include>($$dpth,
            () => {
                let $scope$dir: Nullable<string>;
                let $scope$args: Nullable<nqstring>;
                let $$res: Nullable<include> = null;
                if (true
                    && ((this.matchws($$dpth + 1, $$cr)) || true)
                    && ($scope$dir = this.regexAccept(String.raw`(?:.include)`, "i", $$dpth + 1, $$cr)) !== null
                    && this.matchws($$dpth + 1, $$cr) !== null
                    && ($scope$args = this.matchnqstring($$dpth + 1, $$cr)) !== null
                    && ((this.matchws($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.include, dir: $scope$dir, args: $scope$args};
                }
                return $$res;
            });
    }
    public matchnqstring($$dpth: number, $$cr?: ErrorTracker): Nullable<nqstring> {
        return this.run<nqstring>($$dpth,
            () => {
                let $scope$nq: Nullable<nqstring_$0>;
                let $$res: Nullable<nqstring> = null;
                if (true
                    && ($scope$nq = this.matchnqstring_$0($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.nqstring, nq: $scope$nq};
                }
                return $$res;
            });
    }
    public matchnqstring_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<nqstring_$0> {
        return this.choice<nqstring_$0>([
            () => this.matchnqstring_$0_1($$dpth + 1, $$cr),
            () => this.matchnqstring_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchnqstring_$0_1($$dpth: number, $$cr?: ErrorTracker): Nullable<nqstring_$0_1> {
        return this.matchqstring($$dpth + 1, $$cr);
    }
    public matchnqstring_$0_2($$dpth: number, $$cr?: ErrorTracker): Nullable<nqstring_$0_2> {
        return this.matchwords($$dpth + 1, $$cr);
    }
    public matchqstring($$dpth: number, $$cr?: ErrorTracker): Nullable<qstring> {
        return this.run<qstring>($$dpth,
            () => {
                let $scope$v: Nullable<string>;
                let $$res: Nullable<qstring> = null;
                if (true
                    && this.regexAccept(String.raw`(?:")`, "", $$dpth + 1, $$cr) !== null
                    && ($scope$v = this.regexAccept(String.raw`(?:[^"]*)`, "", $$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:")`, "", $$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.qstring, v: $scope$v};
                }
                return $$res;
            });
    }
    public matchwords($$dpth: number, $$cr?: ErrorTracker): Nullable<words> {
        return this.run<words>($$dpth,
            () => {
                let $scope$w: Nullable<words_$0>;
                let $$res: Nullable<words> = null;
                if (true
                    && ($scope$w = this.matchwords_$0($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.words, w: $scope$w};
                }
                return $$res;
            });
    }
    public matchwords_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<words_$0> {
        return this.run<words_$0>($$dpth,
            () => {
                let $$res: Nullable<words_$0> = null;
                if (true
                    && this.negate(() => this.regexAccept(String.raw`(?:")`, "", $$dpth + 1, $$cr)) !== null
                    && this.negate(() => this.regexAccept(String.raw`(?:\s)`, "", $$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:.*\S)`, "", $$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.words_$0, };
                }
                return $$res;
            });
    }
    public matchunimplemented($$dpth: number, $$cr?: ErrorTracker): Nullable<unimplemented> {
        return this.regexAccept(String.raw`(?:##################################)`, "", $$dpth + 1, $$cr);
    }
    public test(): boolean {
        const mrk = this.mark();
        const res = this.matchline(0);
        const ans = res !== null;
        this.reset(mrk);
        return ans;
    }
    public parse(): ParseResult {
        const mrk = this.mark();
        const res = this.matchline(0);
        if (res)
            return {ast: res, errs: []};
        this.reset(mrk);
        const rec = new ErrorTracker();
        this.clearMemos();
        this.matchline(0, rec);
        const err = rec.getErr()
        return {ast: res, errs: err !== null ? [err] : []}
    }
    public mark(): PosInfo {
        return this.pos;
    }
    // @ts-ignore: loopPlus may not be called
    private loopPlus<T>(func: $$RuleType<T>): Nullable<[T, ...T[]]> {
        return this.loop(func, 1, -1) as Nullable<[T, ...T[]]>;
    }
    private loop<T>(func: $$RuleType<T>, lb: number, ub: number): Nullable<T[]> {
        const mrk = this.mark();
        const res: T[] = [];
        while (ub === -1 || res.length < ub) {
            const preMrk = this.mark();
            const t = func();
            if (t === null || this.pos.overallPos === preMrk.overallPos) {
                break;
            }
            res.push(t);
        }
        if (res.length >= lb) {
            return res;
        }
        this.reset(mrk);
        return null;
    }
    private run<T>($$dpth: number, fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn()
        if (res !== null)
            return res;
        this.reset(mrk);
        return null;
    }
    // @ts-ignore: choice may not be called
    private choice<T>(fns: Array<$$RuleType<T>>): Nullable<T> {
        for (const f of fns) {
            const res = f();
            if (res !== null) {
                return res;
            }
        }
        return null;
    }
    private regexAccept(match: string, mods: string, dpth: number, cr?: ErrorTracker): Nullable<string> {
        return this.run<string>(dpth,
            () => {
                const reg = new RegExp(match, "y" + mods);
                const mrk = this.mark();
                reg.lastIndex = mrk.overallPos;
                const res = this.tryConsume(reg);
                if(cr) {
                    cr.record(mrk, res, {
                        kind: "RegexMatch",
                        // We substring from 3 to len - 1 to strip off the
                        // non-capture group syntax added as a WebKit workaround
                        literal: match.substring(3, match.length - 1),
                        negated: this.negating,
                    });
                }
                return res;
            });
    }
    private tryConsume(reg: RegExp): Nullable<string> {
        const res = reg.exec(this.input);
        if (res) {
            let lineJmp = 0;
            let lind = -1;
            for (let i = 0; i < res[0].length; ++i) {
                if (res[0][i] === "\n") {
                    ++lineJmp;
                    lind = i;
                }
            }
            this.pos = {
                overallPos: reg.lastIndex,
                line: this.pos.line + lineJmp,
                offset: lind === -1 ? this.pos.offset + res[0].length : (res[0].length - lind - 1)
            };
            return res[0];
        }
        return null;
    }
    // @ts-ignore: noConsume may not be called
    private noConsume<T>(fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn();
        this.reset(mrk);
        return res;
    }
    // @ts-ignore: negate may not be called
    private negate<T>(fn: $$RuleType<T>): Nullable<boolean> {
        const mrk = this.mark();
        const oneg = this.negating;
        this.negating = !oneg;
        const res = fn();
        this.negating = oneg;
        this.reset(mrk);
        return res === null ? true : null;
    }
    // @ts-ignore: Memoise may not be used
    private memoise<K>(rule: $$RuleType<K>, memo: Map<number, [Nullable<K>, PosInfo]>): Nullable<K> {
        const $scope$pos = this.mark();
        const $scope$memoRes = memo.get($scope$pos.overallPos);
        if(this.memoSafe && $scope$memoRes !== undefined) {
        this.reset($scope$memoRes[1]);
        return $scope$memoRes[0];
        }
        const $scope$result = rule();
        if(this.memoSafe)
        memo.set($scope$pos.overallPos, [$scope$result, this.mark()]);
        return $scope$result;
    }
    private match$EOF(et?: ErrorTracker): Nullable<{kind: ASTKinds.$EOF}> {
        const res: {kind: ASTKinds.$EOF} | null = this.finished() ? { kind: ASTKinds.$EOF } : null;
        if(et)
            et.record(this.mark(), res, { kind: "EOF", negated: this.negating });
        return res;
    }
}
export function parse(s: string): ParseResult {
    const p = new Parser(s);
    return p.parse();
}
export interface ParseResult {
    ast: Nullable<line>;
    errs: SyntaxErr[];
}
export interface PosInfo {
    readonly overallPos: number;
    readonly line: number;
    readonly offset: number;
}
export interface RegexMatch {
    readonly kind: "RegexMatch";
    readonly negated: boolean;
    readonly literal: string;
}
export type EOFMatch = { kind: "EOF"; negated: boolean };
export type MatchAttempt = RegexMatch | EOFMatch;
export class SyntaxErr {
    public pos: PosInfo;
    public expmatches: MatchAttempt[];
    constructor(pos: PosInfo, expmatches: MatchAttempt[]) {
        this.pos = pos;
        this.expmatches = [...expmatches];
    }
    public toString(): string {
        return `Syntax Error at line ${this.pos.line}:${this.pos.offset}. Expected one of ${this.expmatches.map(x => x.kind === "EOF" ? " EOF" : ` ${x.negated ? 'not ': ''}'${x.literal}'`)}`;
    }
}
class ErrorTracker {
    private mxpos: PosInfo = {overallPos: -1, line: -1, offset: -1};
    private regexset: Set<string> = new Set();
    private pmatches: MatchAttempt[] = [];
    public record(pos: PosInfo, result: any, att: MatchAttempt): void {
        if ((result === null) === att.negated)
            return;
        if (pos.overallPos > this.mxpos.overallPos) {
            this.mxpos = pos;
            this.pmatches = [];
            this.regexset.clear()
        }
        if (this.mxpos.overallPos === pos.overallPos) {
            if(att.kind === "RegexMatch") {
                if(!this.regexset.has(att.literal))
                    this.pmatches.push(att);
                this.regexset.add(att.literal);
            } else {
                this.pmatches.push(att);
            }
        }
    }
    public getErr(): SyntaxErr | null {
        if (this.mxpos.overallPos !== -1)
            return new SyntaxErr(this.mxpos, this.pmatches);
        return null;
    }
}