/* AutoGenerated Code, changes may be overwritten
 * INPUT GRAMMAR:
 * line := t={ linecomment | instruction } $
 * linecomment := lc='[*;].*'
 * instruction := s={ws? | codeline} sc=comment?
 * ws := skip='\s+'
 * comment := ';.*'
 * codeline := l=label? c=content?
 * label := label=identifier ws? c=':'?
 * identifier := '@?[a-zA-Z_][a-zA-Z0-9_]*'
 * content := { opcode | directive }
 * opcode := unimplemented
 * directive := d={title | include | org | unimplemented}
 * title := ws? dir='.title'i ws? ws args=nqstring ws?
 * include := ws? dir='.include'i ws? ws args=nqstring ws?
 * org := ws? dir='.org'i ws? ws args=expr ws?
 * nqstring := nq={qstring | words}
 * qstring := '"' v='[^"]*' '"'
 * words := w={!'"' !'\s' '.*\S'}
 * expr := v=or_expr
 * or_expr := v={xor_expr | or_expr ws? OR_OP ws? xor_expr}
 * xor_expr := v={and_expr | xor_expr ws? XOR_OP ws? and_expr}
 * and_expr := v={equality_expr | and_expr ws? AND_OP ws? equality_expr}
 * equality_expr := v={relational_expr | equality_expr ws? EQ ws? relational_expr | equality_expr ws? ASSIGN ws? relational_expr | equality_expr ws? NE ws? relational_expr}
 * relational_expr := v={additive_expr | relational_expr ws? LT ws? additive_expr | relational_expr ws? GT ws? additive_expr | relational_expr ws? LE ws? additive_expr | relational_expr ws? GE ws? additive_expr}
 * additive_expr := v={multiplicative_expr | additive_expr ws? PLUS ws? multiplicative_expr | additive_expr ws? MINUS ws? multiplicative_expr}
 * multiplicative_expr := v={unary_expr | multiplicative_expr ws? STAR ws? unary_expr | multiplicative_expr ws? DIV ws? unary_expr | multiplicative_expr ws? MOD ws? unary_expr}
 * unary_expr := v={primary_expr | PLUS ws? unary_expr | MINUS ws? unary_expr | BITNOT ws? unary_expr | LNOT ws? unary_expr | LT ws? unary_expr | GT ws? unary_expr}
 * primary_expr := v={number_ | STRING | IDENT | STAR | LPAREN ws? expr ws? RPAREN}
 * number_ := v={ DECNUM | HEXNUM | OCTNUM | BINNUM }
 * OR_OP := '|'
 * XOR_OP := '^'
 * AND_OP := '&'
 * EQ := '=='
 * ASSIGN := '='
 * NE := '!='
 * LT := '<'
 * GT := '>'
 * LE := '<='
 * GE := '>='
 * PLUS := '\+'
 * MINUS := '-'
 * STAR := '\*'
 * DIV := '/'
 * MOD := '%'
 * BITNOT := '~'
 * LNOT := '!'
 * LPAREN := '\('
 * RPAREN := '\)'
 * STRING :='\"' str='([^\"\\]|\\.)*' '\"'
 * IDENT := '@?[a-zA-Z_][a-zA-Z0-9_]*'
 * DECNUM := '[0-9]+'
 * HEXNUM := '(0x|\$)[0-9a-fA-F]+'
 * OCTNUM := '0o[0-7]+'
 * BINNUM := '0b[01]+'
 * unimplemented := '##################################'
 */
type Nullable<T> = T | null;
type $$RuleType<T> = () => Nullable<T>;
export interface ASTNodeIntf {
  kind: ASTKinds;
}
export enum ASTKinds {
  line = "line",
  line_$0_1 = "line_$0_1",
  line_$0_2 = "line_$0_2",
  linecomment = "linecomment",
  instruction = "instruction",
  instruction_$0_1 = "instruction_$0_1",
  instruction_$0_2 = "instruction_$0_2",
  ws = "ws",
  comment = "comment",
  codeline = "codeline",
  label = "label",
  identifier = "identifier",
  content = "content",
  content_$0_1 = "content_$0_1",
  content_$0_2 = "content_$0_2",
  opcode = "opcode",
  directive = "directive",
  directive_$0_1 = "directive_$0_1",
  directive_$0_2 = "directive_$0_2",
  directive_$0_3 = "directive_$0_3",
  directive_$0_4 = "directive_$0_4",
  title = "title",
  include = "include",
  org = "org",
  nqstring = "nqstring",
  nqstring_$0_1 = "nqstring_$0_1",
  nqstring_$0_2 = "nqstring_$0_2",
  qstring = "qstring",
  words = "words",
  words_$0 = "words_$0",
  expr = "expr",
  or_expr = "or_expr",
  or_expr_$0_1 = "or_expr_$0_1",
  or_expr_$0_2 = "or_expr_$0_2",
  xor_expr = "xor_expr",
  xor_expr_$0_1 = "xor_expr_$0_1",
  xor_expr_$0_2 = "xor_expr_$0_2",
  and_expr = "and_expr",
  and_expr_$0_1 = "and_expr_$0_1",
  and_expr_$0_2 = "and_expr_$0_2",
  equality_expr = "equality_expr",
  equality_expr_$0_1 = "equality_expr_$0_1",
  equality_expr_$0_2 = "equality_expr_$0_2",
  equality_expr_$0_3 = "equality_expr_$0_3",
  equality_expr_$0_4 = "equality_expr_$0_4",
  relational_expr = "relational_expr",
  relational_expr_$0_1 = "relational_expr_$0_1",
  relational_expr_$0_2 = "relational_expr_$0_2",
  relational_expr_$0_3 = "relational_expr_$0_3",
  relational_expr_$0_4 = "relational_expr_$0_4",
  relational_expr_$0_5 = "relational_expr_$0_5",
  additive_expr = "additive_expr",
  additive_expr_$0_1 = "additive_expr_$0_1",
  additive_expr_$0_2 = "additive_expr_$0_2",
  additive_expr_$0_3 = "additive_expr_$0_3",
  multiplicative_expr = "multiplicative_expr",
  multiplicative_expr_$0_1 = "multiplicative_expr_$0_1",
  multiplicative_expr_$0_2 = "multiplicative_expr_$0_2",
  multiplicative_expr_$0_3 = "multiplicative_expr_$0_3",
  multiplicative_expr_$0_4 = "multiplicative_expr_$0_4",
  unary_expr = "unary_expr",
  unary_expr_$0_1 = "unary_expr_$0_1",
  unary_expr_$0_2 = "unary_expr_$0_2",
  unary_expr_$0_3 = "unary_expr_$0_3",
  unary_expr_$0_4 = "unary_expr_$0_4",
  unary_expr_$0_5 = "unary_expr_$0_5",
  unary_expr_$0_6 = "unary_expr_$0_6",
  unary_expr_$0_7 = "unary_expr_$0_7",
  primary_expr = "primary_expr",
  primary_expr_$0_1 = "primary_expr_$0_1",
  primary_expr_$0_2 = "primary_expr_$0_2",
  primary_expr_$0_3 = "primary_expr_$0_3",
  primary_expr_$0_4 = "primary_expr_$0_4",
  primary_expr_$0_5 = "primary_expr_$0_5",
  number_ = "number_",
  number__$0_1 = "number__$0_1",
  number__$0_2 = "number__$0_2",
  number__$0_3 = "number__$0_3",
  number__$0_4 = "number__$0_4",
  OR_OP = "OR_OP",
  XOR_OP = "XOR_OP",
  AND_OP = "AND_OP",
  EQ = "EQ",
  ASSIGN = "ASSIGN",
  NE = "NE",
  LT = "LT",
  GT = "GT",
  LE = "LE",
  GE = "GE",
  PLUS = "PLUS",
  MINUS = "MINUS",
  STAR = "STAR",
  DIV = "DIV",
  MOD = "MOD",
  BITNOT = "BITNOT",
  LNOT = "LNOT",
  LPAREN = "LPAREN",
  RPAREN = "RPAREN",
  STRING = "STRING",
  IDENT = "IDENT",
  DECNUM = "DECNUM",
  HEXNUM = "HEXNUM",
  OCTNUM = "OCTNUM",
  BINNUM = "BINNUM",
  unimplemented = "unimplemented",
  $EOF = "$EOF",
}
export interface line {
  kind: ASTKinds.line;
  t: line_$0;
}
export type line_$0 = line_$0_1 | line_$0_2;
export type line_$0_1 = linecomment;
export type line_$0_2 = instruction;
export interface linecomment {
  kind: ASTKinds.linecomment;
  lc: string;
}
export interface instruction {
  kind: ASTKinds.instruction;
  s: instruction_$0;
  sc: Nullable<comment>;
}
export type instruction_$0 = instruction_$0_1 | instruction_$0_2;
export type instruction_$0_1 = Nullable<ws>;
export type instruction_$0_2 = codeline;
export interface ws {
  kind: ASTKinds.ws;
  skip: string;
}
export type comment = string;
export interface codeline {
  kind: ASTKinds.codeline;
  l: Nullable<label>;
  c: Nullable<content>;
}
export interface label {
  kind: ASTKinds.label;
  label: identifier;
  c: Nullable<string>;
}
export type identifier = string;
export type content = content_$0;
export type content_$0 = content_$0_1 | content_$0_2;
export type content_$0_1 = opcode;
export type content_$0_2 = directive;
export type opcode = unimplemented;
export interface directive {
  kind: ASTKinds.directive;
  d: directive_$0;
}
export type directive_$0 =
  | directive_$0_1
  | directive_$0_2
  | directive_$0_3
  | directive_$0_4;
export type directive_$0_1 = title;
export type directive_$0_2 = include;
export type directive_$0_3 = org;
export type directive_$0_4 = unimplemented;
export interface title {
  kind: ASTKinds.title;
  dir: string;
  args: nqstring;
}
export interface include {
  kind: ASTKinds.include;
  dir: string;
  args: nqstring;
}
export interface org {
  kind: ASTKinds.org;
  dir: string;
  args: expr;
}
export interface nqstring {
  kind: ASTKinds.nqstring;
  nq: nqstring_$0;
}
export type nqstring_$0 = nqstring_$0_1 | nqstring_$0_2;
export type nqstring_$0_1 = qstring;
export type nqstring_$0_2 = words;
export interface qstring {
  kind: ASTKinds.qstring;
  v: string;
}
export interface words {
  kind: ASTKinds.words;
  w: words_$0;
}
export interface words_$0 {
  kind: ASTKinds.words_$0;
}
export interface expr {
  kind: ASTKinds.expr;
  v: or_expr;
}
export interface or_expr {
  kind: ASTKinds.or_expr;
  v: or_expr_$0;
}
export type or_expr_$0 = or_expr_$0_1 | or_expr_$0_2;
export type or_expr_$0_1 = xor_expr;
export interface or_expr_$0_2 {
  kind: ASTKinds.or_expr_$0_2;
}
export interface xor_expr {
  kind: ASTKinds.xor_expr;
  v: xor_expr_$0;
}
export type xor_expr_$0 = xor_expr_$0_1 | xor_expr_$0_2;
export type xor_expr_$0_1 = and_expr;
export interface xor_expr_$0_2 {
  kind: ASTKinds.xor_expr_$0_2;
}
export interface and_expr {
  kind: ASTKinds.and_expr;
  v: and_expr_$0;
}
export type and_expr_$0 = and_expr_$0_1 | and_expr_$0_2;
export type and_expr_$0_1 = equality_expr;
export interface and_expr_$0_2 {
  kind: ASTKinds.and_expr_$0_2;
}
export interface equality_expr {
  kind: ASTKinds.equality_expr;
  v: equality_expr_$0;
}
export type equality_expr_$0 =
  | equality_expr_$0_1
  | equality_expr_$0_2
  | equality_expr_$0_3
  | equality_expr_$0_4;
export type equality_expr_$0_1 = relational_expr;
export interface equality_expr_$0_2 {
  kind: ASTKinds.equality_expr_$0_2;
}
export interface equality_expr_$0_3 {
  kind: ASTKinds.equality_expr_$0_3;
}
export interface equality_expr_$0_4 {
  kind: ASTKinds.equality_expr_$0_4;
}
export interface relational_expr {
  kind: ASTKinds.relational_expr;
  v: relational_expr_$0;
}
export type relational_expr_$0 =
  | relational_expr_$0_1
  | relational_expr_$0_2
  | relational_expr_$0_3
  | relational_expr_$0_4
  | relational_expr_$0_5;
export type relational_expr_$0_1 = additive_expr;
export interface relational_expr_$0_2 {
  kind: ASTKinds.relational_expr_$0_2;
}
export interface relational_expr_$0_3 {
  kind: ASTKinds.relational_expr_$0_3;
}
export interface relational_expr_$0_4 {
  kind: ASTKinds.relational_expr_$0_4;
}
export interface relational_expr_$0_5 {
  kind: ASTKinds.relational_expr_$0_5;
}
export interface additive_expr {
  kind: ASTKinds.additive_expr;
  v: additive_expr_$0;
}
export type additive_expr_$0 =
  | additive_expr_$0_1
  | additive_expr_$0_2
  | additive_expr_$0_3;
export type additive_expr_$0_1 = multiplicative_expr;
export interface additive_expr_$0_2 {
  kind: ASTKinds.additive_expr_$0_2;
}
export interface additive_expr_$0_3 {
  kind: ASTKinds.additive_expr_$0_3;
}
export interface multiplicative_expr {
  kind: ASTKinds.multiplicative_expr;
  v: multiplicative_expr_$0;
}
export type multiplicative_expr_$0 =
  | multiplicative_expr_$0_1
  | multiplicative_expr_$0_2
  | multiplicative_expr_$0_3
  | multiplicative_expr_$0_4;
export type multiplicative_expr_$0_1 = unary_expr;
export interface multiplicative_expr_$0_2 {
  kind: ASTKinds.multiplicative_expr_$0_2;
}
export interface multiplicative_expr_$0_3 {
  kind: ASTKinds.multiplicative_expr_$0_3;
}
export interface multiplicative_expr_$0_4 {
  kind: ASTKinds.multiplicative_expr_$0_4;
}
export interface unary_expr {
  kind: ASTKinds.unary_expr;
  v: unary_expr_$0;
}
export type unary_expr_$0 =
  | unary_expr_$0_1
  | unary_expr_$0_2
  | unary_expr_$0_3
  | unary_expr_$0_4
  | unary_expr_$0_5
  | unary_expr_$0_6
  | unary_expr_$0_7;
export type unary_expr_$0_1 = primary_expr;
export interface unary_expr_$0_2 {
  kind: ASTKinds.unary_expr_$0_2;
}
export interface unary_expr_$0_3 {
  kind: ASTKinds.unary_expr_$0_3;
}
export interface unary_expr_$0_4 {
  kind: ASTKinds.unary_expr_$0_4;
}
export interface unary_expr_$0_5 {
  kind: ASTKinds.unary_expr_$0_5;
}
export interface unary_expr_$0_6 {
  kind: ASTKinds.unary_expr_$0_6;
}
export interface unary_expr_$0_7 {
  kind: ASTKinds.unary_expr_$0_7;
}
export interface primary_expr {
  kind: ASTKinds.primary_expr;
  v: primary_expr_$0;
}
export type primary_expr_$0 =
  | primary_expr_$0_1
  | primary_expr_$0_2
  | primary_expr_$0_3
  | primary_expr_$0_4
  | primary_expr_$0_5;
export type primary_expr_$0_1 = number_;
export type primary_expr_$0_2 = STRING;
export type primary_expr_$0_3 = IDENT;
export type primary_expr_$0_4 = STAR;
export interface primary_expr_$0_5 {
  kind: ASTKinds.primary_expr_$0_5;
}
export interface number_ {
  kind: ASTKinds.number_;
  v: number__$0;
}
export type number__$0 =
  | number__$0_1
  | number__$0_2
  | number__$0_3
  | number__$0_4;
export type number__$0_1 = DECNUM;
export type number__$0_2 = HEXNUM;
export type number__$0_3 = OCTNUM;
export type number__$0_4 = BINNUM;
export type OR_OP = string;
export type XOR_OP = string;
export type AND_OP = string;
export type EQ = string;
export type ASSIGN = string;
export type NE = string;
export type LT = string;
export type GT = string;
export type LE = string;
export type GE = string;
export type PLUS = string;
export type MINUS = string;
export type STAR = string;
export type DIV = string;
export type MOD = string;
export type BITNOT = string;
export type LNOT = string;
export type LPAREN = string;
export type RPAREN = string;
export interface STRING {
  kind: ASTKinds.STRING;
  str: string;
}
export type IDENT = string;
export type DECNUM = string;
export type HEXNUM = string;
export type OCTNUM = string;
export type BINNUM = string;
export type unimplemented = string;
export class Parser {
  private readonly input: string;
  private pos: PosInfo;
  private negating: boolean = false;
  private memoSafe: boolean = true;
  constructor(input: string) {
    this.pos = { overallPos: 0, line: 1, offset: 0 };
    this.input = input;
  }
  public reset(pos: PosInfo): void {
    this.pos = pos;
  }
  public finished(): boolean {
    return this.pos.overallPos === this.input.length;
  }
  public clearMemos(): void {
    this.$scope$or_expr$memo.clear();
    this.$scope$xor_expr$memo.clear();
    this.$scope$and_expr$memo.clear();
    this.$scope$equality_expr$memo.clear();
    this.$scope$relational_expr$memo.clear();
    this.$scope$additive_expr$memo.clear();
    this.$scope$multiplicative_expr$memo.clear();
  }
  protected $scope$or_expr$memo: Map<number, [Nullable<or_expr>, PosInfo]> =
    new Map();
  protected $scope$xor_expr$memo: Map<number, [Nullable<xor_expr>, PosInfo]> =
    new Map();
  protected $scope$and_expr$memo: Map<number, [Nullable<and_expr>, PosInfo]> =
    new Map();
  protected $scope$equality_expr$memo: Map<
    number,
    [Nullable<equality_expr>, PosInfo]
  > = new Map();
  protected $scope$relational_expr$memo: Map<
    number,
    [Nullable<relational_expr>, PosInfo]
  > = new Map();
  protected $scope$additive_expr$memo: Map<
    number,
    [Nullable<additive_expr>, PosInfo]
  > = new Map();
  protected $scope$multiplicative_expr$memo: Map<
    number,
    [Nullable<multiplicative_expr>, PosInfo]
  > = new Map();
  public matchline($$dpth: number, $$cr?: ErrorTracker): Nullable<line> {
    return this.run<line>($$dpth, () => {
      let $scope$t: Nullable<line_$0>;
      let $$res: Nullable<line> = null;
      if (
        true &&
        ($scope$t = this.matchline_$0($$dpth + 1, $$cr)) !== null &&
        this.match$EOF($$cr) !== null
      ) {
        $$res = { kind: ASTKinds.line, t: $scope$t };
      }
      return $$res;
    });
  }
  public matchline_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<line_$0> {
    return this.choice<line_$0>([
      () => this.matchline_$0_1($$dpth + 1, $$cr),
      () => this.matchline_$0_2($$dpth + 1, $$cr),
    ]);
  }
  public matchline_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<line_$0_1> {
    return this.matchlinecomment($$dpth + 1, $$cr);
  }
  public matchline_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<line_$0_2> {
    return this.matchinstruction($$dpth + 1, $$cr);
  }
  public matchlinecomment(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<linecomment> {
    return this.run<linecomment>($$dpth, () => {
      let $scope$lc: Nullable<string>;
      let $$res: Nullable<linecomment> = null;
      if (
        true &&
        ($scope$lc = this.regexAccept(
          String.raw`(?:[*;].*)`,
          "",
          $$dpth + 1,
          $$cr,
        )) !== null
      ) {
        $$res = { kind: ASTKinds.linecomment, lc: $scope$lc };
      }
      return $$res;
    });
  }
  public matchinstruction(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<instruction> {
    return this.run<instruction>($$dpth, () => {
      let $scope$s: Nullable<instruction_$0>;
      let $scope$sc: Nullable<Nullable<comment>>;
      let $$res: Nullable<instruction> = null;
      if (
        true &&
        ($scope$s = this.matchinstruction_$0($$dpth + 1, $$cr)) !== null &&
        (($scope$sc = this.matchcomment($$dpth + 1, $$cr)) || true)
      ) {
        $$res = { kind: ASTKinds.instruction, s: $scope$s, sc: $scope$sc };
      }
      return $$res;
    });
  }
  public matchinstruction_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<instruction_$0> {
    return this.choice<instruction_$0>([
      () => this.matchinstruction_$0_1($$dpth + 1, $$cr),
      () => this.matchinstruction_$0_2($$dpth + 1, $$cr),
    ]);
  }
  public matchinstruction_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<instruction_$0_1> {
    return this.matchws($$dpth + 1, $$cr);
  }
  public matchinstruction_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<instruction_$0_2> {
    return this.matchcodeline($$dpth + 1, $$cr);
  }
  public matchws($$dpth: number, $$cr?: ErrorTracker): Nullable<ws> {
    return this.run<ws>($$dpth, () => {
      let $scope$skip: Nullable<string>;
      let $$res: Nullable<ws> = null;
      if (
        true &&
        ($scope$skip = this.regexAccept(
          String.raw`(?:\s+)`,
          "",
          $$dpth + 1,
          $$cr,
        )) !== null
      ) {
        $$res = { kind: ASTKinds.ws, skip: $scope$skip };
      }
      return $$res;
    });
  }
  public matchcomment($$dpth: number, $$cr?: ErrorTracker): Nullable<comment> {
    return this.regexAccept(String.raw`(?:;.*)`, "", $$dpth + 1, $$cr);
  }
  public matchcodeline(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<codeline> {
    return this.run<codeline>($$dpth, () => {
      let $scope$l: Nullable<Nullable<label>>;
      let $scope$c: Nullable<Nullable<content>>;
      let $$res: Nullable<codeline> = null;
      if (
        true &&
        (($scope$l = this.matchlabel($$dpth + 1, $$cr)) || true) &&
        (($scope$c = this.matchcontent($$dpth + 1, $$cr)) || true)
      ) {
        $$res = { kind: ASTKinds.codeline, l: $scope$l, c: $scope$c };
      }
      return $$res;
    });
  }
  public matchlabel($$dpth: number, $$cr?: ErrorTracker): Nullable<label> {
    return this.run<label>($$dpth, () => {
      let $scope$label: Nullable<identifier>;
      let $scope$c: Nullable<Nullable<string>>;
      let $$res: Nullable<label> = null;
      if (
        true &&
        ($scope$label = this.matchidentifier($$dpth + 1, $$cr)) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        (($scope$c = this.regexAccept(
          String.raw`(?::)`,
          "",
          $$dpth + 1,
          $$cr,
        )) ||
          true)
      ) {
        $$res = { kind: ASTKinds.label, label: $scope$label, c: $scope$c };
      }
      return $$res;
    });
  }
  public matchidentifier(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<identifier> {
    return this.regexAccept(
      String.raw`(?:@?[a-zA-Z_][a-zA-Z0-9_]*)`,
      "",
      $$dpth + 1,
      $$cr,
    );
  }
  public matchcontent($$dpth: number, $$cr?: ErrorTracker): Nullable<content> {
    return this.matchcontent_$0($$dpth + 1, $$cr);
  }
  public matchcontent_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<content_$0> {
    return this.choice<content_$0>([
      () => this.matchcontent_$0_1($$dpth + 1, $$cr),
      () => this.matchcontent_$0_2($$dpth + 1, $$cr),
    ]);
  }
  public matchcontent_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<content_$0_1> {
    return this.matchopcode($$dpth + 1, $$cr);
  }
  public matchcontent_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<content_$0_2> {
    return this.matchdirective($$dpth + 1, $$cr);
  }
  public matchopcode($$dpth: number, $$cr?: ErrorTracker): Nullable<opcode> {
    return this.matchunimplemented($$dpth + 1, $$cr);
  }
  public matchdirective(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<directive> {
    return this.run<directive>($$dpth, () => {
      let $scope$d: Nullable<directive_$0>;
      let $$res: Nullable<directive> = null;
      if (
        true &&
        ($scope$d = this.matchdirective_$0($$dpth + 1, $$cr)) !== null
      ) {
        $$res = { kind: ASTKinds.directive, d: $scope$d };
      }
      return $$res;
    });
  }
  public matchdirective_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<directive_$0> {
    return this.choice<directive_$0>([
      () => this.matchdirective_$0_1($$dpth + 1, $$cr),
      () => this.matchdirective_$0_2($$dpth + 1, $$cr),
      () => this.matchdirective_$0_3($$dpth + 1, $$cr),
      () => this.matchdirective_$0_4($$dpth + 1, $$cr),
    ]);
  }
  public matchdirective_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<directive_$0_1> {
    return this.matchtitle($$dpth + 1, $$cr);
  }
  public matchdirective_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<directive_$0_2> {
    return this.matchinclude($$dpth + 1, $$cr);
  }
  public matchdirective_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<directive_$0_3> {
    return this.matchorg($$dpth + 1, $$cr);
  }
  public matchdirective_$0_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<directive_$0_4> {
    return this.matchunimplemented($$dpth + 1, $$cr);
  }
  public matchtitle($$dpth: number, $$cr?: ErrorTracker): Nullable<title> {
    return this.run<title>($$dpth, () => {
      let $scope$dir: Nullable<string>;
      let $scope$args: Nullable<nqstring>;
      let $$res: Nullable<title> = null;
      if (
        true &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        ($scope$dir = this.regexAccept(
          String.raw`(?:.title)`,
          "i",
          $$dpth + 1,
          $$cr,
        )) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchws($$dpth + 1, $$cr) !== null &&
        ($scope$args = this.matchnqstring($$dpth + 1, $$cr)) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.title, dir: $scope$dir, args: $scope$args };
      }
      return $$res;
    });
  }
  public matchinclude($$dpth: number, $$cr?: ErrorTracker): Nullable<include> {
    return this.run<include>($$dpth, () => {
      let $scope$dir: Nullable<string>;
      let $scope$args: Nullable<nqstring>;
      let $$res: Nullable<include> = null;
      if (
        true &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        ($scope$dir = this.regexAccept(
          String.raw`(?:.include)`,
          "i",
          $$dpth + 1,
          $$cr,
        )) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchws($$dpth + 1, $$cr) !== null &&
        ($scope$args = this.matchnqstring($$dpth + 1, $$cr)) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.include, dir: $scope$dir, args: $scope$args };
      }
      return $$res;
    });
  }
  public matchorg($$dpth: number, $$cr?: ErrorTracker): Nullable<org> {
    return this.run<org>($$dpth, () => {
      let $scope$dir: Nullable<string>;
      let $scope$args: Nullable<expr>;
      let $$res: Nullable<org> = null;
      if (
        true &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        ($scope$dir = this.regexAccept(
          String.raw`(?:.org)`,
          "i",
          $$dpth + 1,
          $$cr,
        )) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchws($$dpth + 1, $$cr) !== null &&
        ($scope$args = this.matchexpr($$dpth + 1, $$cr)) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.org, dir: $scope$dir, args: $scope$args };
      }
      return $$res;
    });
  }
  public matchnqstring(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<nqstring> {
    return this.run<nqstring>($$dpth, () => {
      let $scope$nq: Nullable<nqstring_$0>;
      let $$res: Nullable<nqstring> = null;
      if (
        true &&
        ($scope$nq = this.matchnqstring_$0($$dpth + 1, $$cr)) !== null
      ) {
        $$res = { kind: ASTKinds.nqstring, nq: $scope$nq };
      }
      return $$res;
    });
  }
  public matchnqstring_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<nqstring_$0> {
    return this.choice<nqstring_$0>([
      () => this.matchnqstring_$0_1($$dpth + 1, $$cr),
      () => this.matchnqstring_$0_2($$dpth + 1, $$cr),
    ]);
  }
  public matchnqstring_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<nqstring_$0_1> {
    return this.matchqstring($$dpth + 1, $$cr);
  }
  public matchnqstring_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<nqstring_$0_2> {
    return this.matchwords($$dpth + 1, $$cr);
  }
  public matchqstring($$dpth: number, $$cr?: ErrorTracker): Nullable<qstring> {
    return this.run<qstring>($$dpth, () => {
      let $scope$v: Nullable<string>;
      let $$res: Nullable<qstring> = null;
      if (
        true &&
        this.regexAccept(String.raw`(?:")`, "", $$dpth + 1, $$cr) !== null &&
        ($scope$v = this.regexAccept(
          String.raw`(?:[^"]*)`,
          "",
          $$dpth + 1,
          $$cr,
        )) !== null &&
        this.regexAccept(String.raw`(?:")`, "", $$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.qstring, v: $scope$v };
      }
      return $$res;
    });
  }
  public matchwords($$dpth: number, $$cr?: ErrorTracker): Nullable<words> {
    return this.run<words>($$dpth, () => {
      let $scope$w: Nullable<words_$0>;
      let $$res: Nullable<words> = null;
      if (true && ($scope$w = this.matchwords_$0($$dpth + 1, $$cr)) !== null) {
        $$res = { kind: ASTKinds.words, w: $scope$w };
      }
      return $$res;
    });
  }
  public matchwords_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<words_$0> {
    return this.run<words_$0>($$dpth, () => {
      let $$res: Nullable<words_$0> = null;
      if (
        true &&
        this.negate(() =>
          this.regexAccept(String.raw`(?:")`, "", $$dpth + 1, $$cr),
        ) !== null &&
        this.negate(() =>
          this.regexAccept(String.raw`(?:\s)`, "", $$dpth + 1, $$cr),
        ) !== null &&
        this.regexAccept(String.raw`(?:.*\S)`, "", $$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.words_$0 };
      }
      return $$res;
    });
  }
  public matchexpr($$dpth: number, $$cr?: ErrorTracker): Nullable<expr> {
    return this.run<expr>($$dpth, () => {
      let $scope$v: Nullable<or_expr>;
      let $$res: Nullable<expr> = null;
      if (true && ($scope$v = this.matchor_expr($$dpth + 1, $$cr)) !== null) {
        $$res = { kind: ASTKinds.expr, v: $scope$v };
      }
      return $$res;
    });
  }
  public matchor_expr($$dpth: number, $$cr?: ErrorTracker): Nullable<or_expr> {
    const fn = () => {
      return this.run<or_expr>($$dpth, () => {
        let $scope$v: Nullable<or_expr_$0>;
        let $$res: Nullable<or_expr> = null;
        if (
          true &&
          ($scope$v = this.matchor_expr_$0($$dpth + 1, $$cr)) !== null
        ) {
          $$res = { kind: ASTKinds.or_expr, v: $scope$v };
        }
        return $$res;
      });
    };
    const $scope$pos = this.mark();
    const memo = this.$scope$or_expr$memo.get($scope$pos.overallPos);
    if (memo !== undefined) {
      this.reset(memo[1]);
      return memo[0];
    }
    const $scope$oldMemoSafe = this.memoSafe;
    this.memoSafe = false;
    this.$scope$or_expr$memo.set($scope$pos.overallPos, [null, $scope$pos]);
    let lastRes: Nullable<or_expr> = null;
    let lastPos: PosInfo = $scope$pos;
    for (;;) {
      this.reset($scope$pos);
      const res = fn();
      const end = this.mark();
      if (end.overallPos <= lastPos.overallPos) break;
      lastRes = res;
      lastPos = end;
      this.$scope$or_expr$memo.set($scope$pos.overallPos, [lastRes, lastPos]);
    }
    this.reset(lastPos);
    this.memoSafe = $scope$oldMemoSafe;
    return lastRes;
  }
  public matchor_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<or_expr_$0> {
    return this.choice<or_expr_$0>([
      () => this.matchor_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchor_expr_$0_2($$dpth + 1, $$cr),
    ]);
  }
  public matchor_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<or_expr_$0_1> {
    return this.matchxor_expr($$dpth + 1, $$cr);
  }
  public matchor_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<or_expr_$0_2> {
    return this.run<or_expr_$0_2>($$dpth, () => {
      let $$res: Nullable<or_expr_$0_2> = null;
      if (
        true &&
        this.matchor_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchOR_OP($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchxor_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.or_expr_$0_2 };
      }
      return $$res;
    });
  }
  public matchxor_expr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<xor_expr> {
    const fn = () => {
      return this.run<xor_expr>($$dpth, () => {
        let $scope$v: Nullable<xor_expr_$0>;
        let $$res: Nullable<xor_expr> = null;
        if (
          true &&
          ($scope$v = this.matchxor_expr_$0($$dpth + 1, $$cr)) !== null
        ) {
          $$res = { kind: ASTKinds.xor_expr, v: $scope$v };
        }
        return $$res;
      });
    };
    const $scope$pos = this.mark();
    const memo = this.$scope$xor_expr$memo.get($scope$pos.overallPos);
    if (memo !== undefined) {
      this.reset(memo[1]);
      return memo[0];
    }
    const $scope$oldMemoSafe = this.memoSafe;
    this.memoSafe = false;
    this.$scope$xor_expr$memo.set($scope$pos.overallPos, [null, $scope$pos]);
    let lastRes: Nullable<xor_expr> = null;
    let lastPos: PosInfo = $scope$pos;
    for (;;) {
      this.reset($scope$pos);
      const res = fn();
      const end = this.mark();
      if (end.overallPos <= lastPos.overallPos) break;
      lastRes = res;
      lastPos = end;
      this.$scope$xor_expr$memo.set($scope$pos.overallPos, [lastRes, lastPos]);
    }
    this.reset(lastPos);
    this.memoSafe = $scope$oldMemoSafe;
    return lastRes;
  }
  public matchxor_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<xor_expr_$0> {
    return this.choice<xor_expr_$0>([
      () => this.matchxor_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchxor_expr_$0_2($$dpth + 1, $$cr),
    ]);
  }
  public matchxor_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<xor_expr_$0_1> {
    return this.matchand_expr($$dpth + 1, $$cr);
  }
  public matchxor_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<xor_expr_$0_2> {
    return this.run<xor_expr_$0_2>($$dpth, () => {
      let $$res: Nullable<xor_expr_$0_2> = null;
      if (
        true &&
        this.matchxor_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchXOR_OP($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchand_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.xor_expr_$0_2 };
      }
      return $$res;
    });
  }
  public matchand_expr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<and_expr> {
    const fn = () => {
      return this.run<and_expr>($$dpth, () => {
        let $scope$v: Nullable<and_expr_$0>;
        let $$res: Nullable<and_expr> = null;
        if (
          true &&
          ($scope$v = this.matchand_expr_$0($$dpth + 1, $$cr)) !== null
        ) {
          $$res = { kind: ASTKinds.and_expr, v: $scope$v };
        }
        return $$res;
      });
    };
    const $scope$pos = this.mark();
    const memo = this.$scope$and_expr$memo.get($scope$pos.overallPos);
    if (memo !== undefined) {
      this.reset(memo[1]);
      return memo[0];
    }
    const $scope$oldMemoSafe = this.memoSafe;
    this.memoSafe = false;
    this.$scope$and_expr$memo.set($scope$pos.overallPos, [null, $scope$pos]);
    let lastRes: Nullable<and_expr> = null;
    let lastPos: PosInfo = $scope$pos;
    for (;;) {
      this.reset($scope$pos);
      const res = fn();
      const end = this.mark();
      if (end.overallPos <= lastPos.overallPos) break;
      lastRes = res;
      lastPos = end;
      this.$scope$and_expr$memo.set($scope$pos.overallPos, [lastRes, lastPos]);
    }
    this.reset(lastPos);
    this.memoSafe = $scope$oldMemoSafe;
    return lastRes;
  }
  public matchand_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<and_expr_$0> {
    return this.choice<and_expr_$0>([
      () => this.matchand_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchand_expr_$0_2($$dpth + 1, $$cr),
    ]);
  }
  public matchand_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<and_expr_$0_1> {
    return this.matchequality_expr($$dpth + 1, $$cr);
  }
  public matchand_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<and_expr_$0_2> {
    return this.run<and_expr_$0_2>($$dpth, () => {
      let $$res: Nullable<and_expr_$0_2> = null;
      if (
        true &&
        this.matchand_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchAND_OP($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchequality_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.and_expr_$0_2 };
      }
      return $$res;
    });
  }
  public matchequality_expr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<equality_expr> {
    const fn = () => {
      return this.run<equality_expr>($$dpth, () => {
        let $scope$v: Nullable<equality_expr_$0>;
        let $$res: Nullable<equality_expr> = null;
        if (
          true &&
          ($scope$v = this.matchequality_expr_$0($$dpth + 1, $$cr)) !== null
        ) {
          $$res = { kind: ASTKinds.equality_expr, v: $scope$v };
        }
        return $$res;
      });
    };
    const $scope$pos = this.mark();
    const memo = this.$scope$equality_expr$memo.get($scope$pos.overallPos);
    if (memo !== undefined) {
      this.reset(memo[1]);
      return memo[0];
    }
    const $scope$oldMemoSafe = this.memoSafe;
    this.memoSafe = false;
    this.$scope$equality_expr$memo.set($scope$pos.overallPos, [
      null,
      $scope$pos,
    ]);
    let lastRes: Nullable<equality_expr> = null;
    let lastPos: PosInfo = $scope$pos;
    for (;;) {
      this.reset($scope$pos);
      const res = fn();
      const end = this.mark();
      if (end.overallPos <= lastPos.overallPos) break;
      lastRes = res;
      lastPos = end;
      this.$scope$equality_expr$memo.set($scope$pos.overallPos, [
        lastRes,
        lastPos,
      ]);
    }
    this.reset(lastPos);
    this.memoSafe = $scope$oldMemoSafe;
    return lastRes;
  }
  public matchequality_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<equality_expr_$0> {
    return this.choice<equality_expr_$0>([
      () => this.matchequality_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchequality_expr_$0_2($$dpth + 1, $$cr),
      () => this.matchequality_expr_$0_3($$dpth + 1, $$cr),
      () => this.matchequality_expr_$0_4($$dpth + 1, $$cr),
    ]);
  }
  public matchequality_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<equality_expr_$0_1> {
    return this.matchrelational_expr($$dpth + 1, $$cr);
  }
  public matchequality_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<equality_expr_$0_2> {
    return this.run<equality_expr_$0_2>($$dpth, () => {
      let $$res: Nullable<equality_expr_$0_2> = null;
      if (
        true &&
        this.matchequality_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchEQ($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchrelational_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.equality_expr_$0_2 };
      }
      return $$res;
    });
  }
  public matchequality_expr_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<equality_expr_$0_3> {
    return this.run<equality_expr_$0_3>($$dpth, () => {
      let $$res: Nullable<equality_expr_$0_3> = null;
      if (
        true &&
        this.matchequality_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchASSIGN($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchrelational_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.equality_expr_$0_3 };
      }
      return $$res;
    });
  }
  public matchequality_expr_$0_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<equality_expr_$0_4> {
    return this.run<equality_expr_$0_4>($$dpth, () => {
      let $$res: Nullable<equality_expr_$0_4> = null;
      if (
        true &&
        this.matchequality_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchNE($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchrelational_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.equality_expr_$0_4 };
      }
      return $$res;
    });
  }
  public matchrelational_expr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<relational_expr> {
    const fn = () => {
      return this.run<relational_expr>($$dpth, () => {
        let $scope$v: Nullable<relational_expr_$0>;
        let $$res: Nullable<relational_expr> = null;
        if (
          true &&
          ($scope$v = this.matchrelational_expr_$0($$dpth + 1, $$cr)) !== null
        ) {
          $$res = { kind: ASTKinds.relational_expr, v: $scope$v };
        }
        return $$res;
      });
    };
    const $scope$pos = this.mark();
    const memo = this.$scope$relational_expr$memo.get($scope$pos.overallPos);
    if (memo !== undefined) {
      this.reset(memo[1]);
      return memo[0];
    }
    const $scope$oldMemoSafe = this.memoSafe;
    this.memoSafe = false;
    this.$scope$relational_expr$memo.set($scope$pos.overallPos, [
      null,
      $scope$pos,
    ]);
    let lastRes: Nullable<relational_expr> = null;
    let lastPos: PosInfo = $scope$pos;
    for (;;) {
      this.reset($scope$pos);
      const res = fn();
      const end = this.mark();
      if (end.overallPos <= lastPos.overallPos) break;
      lastRes = res;
      lastPos = end;
      this.$scope$relational_expr$memo.set($scope$pos.overallPos, [
        lastRes,
        lastPos,
      ]);
    }
    this.reset(lastPos);
    this.memoSafe = $scope$oldMemoSafe;
    return lastRes;
  }
  public matchrelational_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<relational_expr_$0> {
    return this.choice<relational_expr_$0>([
      () => this.matchrelational_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchrelational_expr_$0_2($$dpth + 1, $$cr),
      () => this.matchrelational_expr_$0_3($$dpth + 1, $$cr),
      () => this.matchrelational_expr_$0_4($$dpth + 1, $$cr),
      () => this.matchrelational_expr_$0_5($$dpth + 1, $$cr),
    ]);
  }
  public matchrelational_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<relational_expr_$0_1> {
    return this.matchadditive_expr($$dpth + 1, $$cr);
  }
  public matchrelational_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<relational_expr_$0_2> {
    return this.run<relational_expr_$0_2>($$dpth, () => {
      let $$res: Nullable<relational_expr_$0_2> = null;
      if (
        true &&
        this.matchrelational_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchLT($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchadditive_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.relational_expr_$0_2 };
      }
      return $$res;
    });
  }
  public matchrelational_expr_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<relational_expr_$0_3> {
    return this.run<relational_expr_$0_3>($$dpth, () => {
      let $$res: Nullable<relational_expr_$0_3> = null;
      if (
        true &&
        this.matchrelational_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchGT($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchadditive_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.relational_expr_$0_3 };
      }
      return $$res;
    });
  }
  public matchrelational_expr_$0_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<relational_expr_$0_4> {
    return this.run<relational_expr_$0_4>($$dpth, () => {
      let $$res: Nullable<relational_expr_$0_4> = null;
      if (
        true &&
        this.matchrelational_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchLE($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchadditive_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.relational_expr_$0_4 };
      }
      return $$res;
    });
  }
  public matchrelational_expr_$0_5(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<relational_expr_$0_5> {
    return this.run<relational_expr_$0_5>($$dpth, () => {
      let $$res: Nullable<relational_expr_$0_5> = null;
      if (
        true &&
        this.matchrelational_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchGE($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchadditive_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.relational_expr_$0_5 };
      }
      return $$res;
    });
  }
  public matchadditive_expr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<additive_expr> {
    const fn = () => {
      return this.run<additive_expr>($$dpth, () => {
        let $scope$v: Nullable<additive_expr_$0>;
        let $$res: Nullable<additive_expr> = null;
        if (
          true &&
          ($scope$v = this.matchadditive_expr_$0($$dpth + 1, $$cr)) !== null
        ) {
          $$res = { kind: ASTKinds.additive_expr, v: $scope$v };
        }
        return $$res;
      });
    };
    const $scope$pos = this.mark();
    const memo = this.$scope$additive_expr$memo.get($scope$pos.overallPos);
    if (memo !== undefined) {
      this.reset(memo[1]);
      return memo[0];
    }
    const $scope$oldMemoSafe = this.memoSafe;
    this.memoSafe = false;
    this.$scope$additive_expr$memo.set($scope$pos.overallPos, [
      null,
      $scope$pos,
    ]);
    let lastRes: Nullable<additive_expr> = null;
    let lastPos: PosInfo = $scope$pos;
    for (;;) {
      this.reset($scope$pos);
      const res = fn();
      const end = this.mark();
      if (end.overallPos <= lastPos.overallPos) break;
      lastRes = res;
      lastPos = end;
      this.$scope$additive_expr$memo.set($scope$pos.overallPos, [
        lastRes,
        lastPos,
      ]);
    }
    this.reset(lastPos);
    this.memoSafe = $scope$oldMemoSafe;
    return lastRes;
  }
  public matchadditive_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<additive_expr_$0> {
    return this.choice<additive_expr_$0>([
      () => this.matchadditive_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchadditive_expr_$0_2($$dpth + 1, $$cr),
      () => this.matchadditive_expr_$0_3($$dpth + 1, $$cr),
    ]);
  }
  public matchadditive_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<additive_expr_$0_1> {
    return this.matchmultiplicative_expr($$dpth + 1, $$cr);
  }
  public matchadditive_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<additive_expr_$0_2> {
    return this.run<additive_expr_$0_2>($$dpth, () => {
      let $$res: Nullable<additive_expr_$0_2> = null;
      if (
        true &&
        this.matchadditive_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchPLUS($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchmultiplicative_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.additive_expr_$0_2 };
      }
      return $$res;
    });
  }
  public matchadditive_expr_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<additive_expr_$0_3> {
    return this.run<additive_expr_$0_3>($$dpth, () => {
      let $$res: Nullable<additive_expr_$0_3> = null;
      if (
        true &&
        this.matchadditive_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchMINUS($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchmultiplicative_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.additive_expr_$0_3 };
      }
      return $$res;
    });
  }
  public matchmultiplicative_expr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<multiplicative_expr> {
    const fn = () => {
      return this.run<multiplicative_expr>($$dpth, () => {
        let $scope$v: Nullable<multiplicative_expr_$0>;
        let $$res: Nullable<multiplicative_expr> = null;
        if (
          true &&
          ($scope$v = this.matchmultiplicative_expr_$0($$dpth + 1, $$cr)) !==
            null
        ) {
          $$res = { kind: ASTKinds.multiplicative_expr, v: $scope$v };
        }
        return $$res;
      });
    };
    const $scope$pos = this.mark();
    const memo = this.$scope$multiplicative_expr$memo.get(
      $scope$pos.overallPos,
    );
    if (memo !== undefined) {
      this.reset(memo[1]);
      return memo[0];
    }
    const $scope$oldMemoSafe = this.memoSafe;
    this.memoSafe = false;
    this.$scope$multiplicative_expr$memo.set($scope$pos.overallPos, [
      null,
      $scope$pos,
    ]);
    let lastRes: Nullable<multiplicative_expr> = null;
    let lastPos: PosInfo = $scope$pos;
    for (;;) {
      this.reset($scope$pos);
      const res = fn();
      const end = this.mark();
      if (end.overallPos <= lastPos.overallPos) break;
      lastRes = res;
      lastPos = end;
      this.$scope$multiplicative_expr$memo.set($scope$pos.overallPos, [
        lastRes,
        lastPos,
      ]);
    }
    this.reset(lastPos);
    this.memoSafe = $scope$oldMemoSafe;
    return lastRes;
  }
  public matchmultiplicative_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<multiplicative_expr_$0> {
    return this.choice<multiplicative_expr_$0>([
      () => this.matchmultiplicative_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchmultiplicative_expr_$0_2($$dpth + 1, $$cr),
      () => this.matchmultiplicative_expr_$0_3($$dpth + 1, $$cr),
      () => this.matchmultiplicative_expr_$0_4($$dpth + 1, $$cr),
    ]);
  }
  public matchmultiplicative_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<multiplicative_expr_$0_1> {
    return this.matchunary_expr($$dpth + 1, $$cr);
  }
  public matchmultiplicative_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<multiplicative_expr_$0_2> {
    return this.run<multiplicative_expr_$0_2>($$dpth, () => {
      let $$res: Nullable<multiplicative_expr_$0_2> = null;
      if (
        true &&
        this.matchmultiplicative_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchSTAR($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.multiplicative_expr_$0_2 };
      }
      return $$res;
    });
  }
  public matchmultiplicative_expr_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<multiplicative_expr_$0_3> {
    return this.run<multiplicative_expr_$0_3>($$dpth, () => {
      let $$res: Nullable<multiplicative_expr_$0_3> = null;
      if (
        true &&
        this.matchmultiplicative_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchDIV($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.multiplicative_expr_$0_3 };
      }
      return $$res;
    });
  }
  public matchmultiplicative_expr_$0_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<multiplicative_expr_$0_4> {
    return this.run<multiplicative_expr_$0_4>($$dpth, () => {
      let $$res: Nullable<multiplicative_expr_$0_4> = null;
      if (
        true &&
        this.matchmultiplicative_expr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchMOD($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.multiplicative_expr_$0_4 };
      }
      return $$res;
    });
  }
  public matchunary_expr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr> {
    return this.run<unary_expr>($$dpth, () => {
      let $scope$v: Nullable<unary_expr_$0>;
      let $$res: Nullable<unary_expr> = null;
      if (
        true &&
        ($scope$v = this.matchunary_expr_$0($$dpth + 1, $$cr)) !== null
      ) {
        $$res = { kind: ASTKinds.unary_expr, v: $scope$v };
      }
      return $$res;
    });
  }
  public matchunary_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr_$0> {
    return this.choice<unary_expr_$0>([
      () => this.matchunary_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchunary_expr_$0_2($$dpth + 1, $$cr),
      () => this.matchunary_expr_$0_3($$dpth + 1, $$cr),
      () => this.matchunary_expr_$0_4($$dpth + 1, $$cr),
      () => this.matchunary_expr_$0_5($$dpth + 1, $$cr),
      () => this.matchunary_expr_$0_6($$dpth + 1, $$cr),
      () => this.matchunary_expr_$0_7($$dpth + 1, $$cr),
    ]);
  }
  public matchunary_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr_$0_1> {
    return this.matchprimary_expr($$dpth + 1, $$cr);
  }
  public matchunary_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr_$0_2> {
    return this.run<unary_expr_$0_2>($$dpth, () => {
      let $$res: Nullable<unary_expr_$0_2> = null;
      if (
        true &&
        this.matchPLUS($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.unary_expr_$0_2 };
      }
      return $$res;
    });
  }
  public matchunary_expr_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr_$0_3> {
    return this.run<unary_expr_$0_3>($$dpth, () => {
      let $$res: Nullable<unary_expr_$0_3> = null;
      if (
        true &&
        this.matchMINUS($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.unary_expr_$0_3 };
      }
      return $$res;
    });
  }
  public matchunary_expr_$0_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr_$0_4> {
    return this.run<unary_expr_$0_4>($$dpth, () => {
      let $$res: Nullable<unary_expr_$0_4> = null;
      if (
        true &&
        this.matchBITNOT($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.unary_expr_$0_4 };
      }
      return $$res;
    });
  }
  public matchunary_expr_$0_5(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr_$0_5> {
    return this.run<unary_expr_$0_5>($$dpth, () => {
      let $$res: Nullable<unary_expr_$0_5> = null;
      if (
        true &&
        this.matchLNOT($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.unary_expr_$0_5 };
      }
      return $$res;
    });
  }
  public matchunary_expr_$0_6(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr_$0_6> {
    return this.run<unary_expr_$0_6>($$dpth, () => {
      let $$res: Nullable<unary_expr_$0_6> = null;
      if (
        true &&
        this.matchLT($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.unary_expr_$0_6 };
      }
      return $$res;
    });
  }
  public matchunary_expr_$0_7(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unary_expr_$0_7> {
    return this.run<unary_expr_$0_7>($$dpth, () => {
      let $$res: Nullable<unary_expr_$0_7> = null;
      if (
        true &&
        this.matchGT($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchunary_expr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.unary_expr_$0_7 };
      }
      return $$res;
    });
  }
  public matchprimary_expr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<primary_expr> {
    return this.run<primary_expr>($$dpth, () => {
      let $scope$v: Nullable<primary_expr_$0>;
      let $$res: Nullable<primary_expr> = null;
      if (
        true &&
        ($scope$v = this.matchprimary_expr_$0($$dpth + 1, $$cr)) !== null
      ) {
        $$res = { kind: ASTKinds.primary_expr, v: $scope$v };
      }
      return $$res;
    });
  }
  public matchprimary_expr_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<primary_expr_$0> {
    return this.choice<primary_expr_$0>([
      () => this.matchprimary_expr_$0_1($$dpth + 1, $$cr),
      () => this.matchprimary_expr_$0_2($$dpth + 1, $$cr),
      () => this.matchprimary_expr_$0_3($$dpth + 1, $$cr),
      () => this.matchprimary_expr_$0_4($$dpth + 1, $$cr),
      () => this.matchprimary_expr_$0_5($$dpth + 1, $$cr),
    ]);
  }
  public matchprimary_expr_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<primary_expr_$0_1> {
    return this.matchnumber_($$dpth + 1, $$cr);
  }
  public matchprimary_expr_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<primary_expr_$0_2> {
    return this.matchSTRING($$dpth + 1, $$cr);
  }
  public matchprimary_expr_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<primary_expr_$0_3> {
    return this.matchIDENT($$dpth + 1, $$cr);
  }
  public matchprimary_expr_$0_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<primary_expr_$0_4> {
    return this.matchSTAR($$dpth + 1, $$cr);
  }
  public matchprimary_expr_$0_5(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<primary_expr_$0_5> {
    return this.run<primary_expr_$0_5>($$dpth, () => {
      let $$res: Nullable<primary_expr_$0_5> = null;
      if (
        true &&
        this.matchLPAREN($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchexpr($$dpth + 1, $$cr) !== null &&
        (this.matchws($$dpth + 1, $$cr) || true) &&
        this.matchRPAREN($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.primary_expr_$0_5 };
      }
      return $$res;
    });
  }
  public matchnumber_($$dpth: number, $$cr?: ErrorTracker): Nullable<number_> {
    return this.run<number_>($$dpth, () => {
      let $scope$v: Nullable<number__$0>;
      let $$res: Nullable<number_> = null;
      if (
        true &&
        ($scope$v = this.matchnumber__$0($$dpth + 1, $$cr)) !== null
      ) {
        $$res = { kind: ASTKinds.number_, v: $scope$v };
      }
      return $$res;
    });
  }
  public matchnumber__$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<number__$0> {
    return this.choice<number__$0>([
      () => this.matchnumber__$0_1($$dpth + 1, $$cr),
      () => this.matchnumber__$0_2($$dpth + 1, $$cr),
      () => this.matchnumber__$0_3($$dpth + 1, $$cr),
      () => this.matchnumber__$0_4($$dpth + 1, $$cr),
    ]);
  }
  public matchnumber__$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<number__$0_1> {
    return this.matchDECNUM($$dpth + 1, $$cr);
  }
  public matchnumber__$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<number__$0_2> {
    return this.matchHEXNUM($$dpth + 1, $$cr);
  }
  public matchnumber__$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<number__$0_3> {
    return this.matchOCTNUM($$dpth + 1, $$cr);
  }
  public matchnumber__$0_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<number__$0_4> {
    return this.matchBINNUM($$dpth + 1, $$cr);
  }
  public matchOR_OP($$dpth: number, $$cr?: ErrorTracker): Nullable<OR_OP> {
    return this.regexAccept(String.raw`(?:|)`, "", $$dpth + 1, $$cr);
  }
  public matchXOR_OP($$dpth: number, $$cr?: ErrorTracker): Nullable<XOR_OP> {
    return this.regexAccept(String.raw`(?:^)`, "", $$dpth + 1, $$cr);
  }
  public matchAND_OP($$dpth: number, $$cr?: ErrorTracker): Nullable<AND_OP> {
    return this.regexAccept(String.raw`(?:&)`, "", $$dpth + 1, $$cr);
  }
  public matchEQ($$dpth: number, $$cr?: ErrorTracker): Nullable<EQ> {
    return this.regexAccept(String.raw`(?:==)`, "", $$dpth + 1, $$cr);
  }
  public matchASSIGN($$dpth: number, $$cr?: ErrorTracker): Nullable<ASSIGN> {
    return this.regexAccept(String.raw`(?:=)`, "", $$dpth + 1, $$cr);
  }
  public matchNE($$dpth: number, $$cr?: ErrorTracker): Nullable<NE> {
    return this.regexAccept(String.raw`(?:!=)`, "", $$dpth + 1, $$cr);
  }
  public matchLT($$dpth: number, $$cr?: ErrorTracker): Nullable<LT> {
    return this.regexAccept(String.raw`(?:<)`, "", $$dpth + 1, $$cr);
  }
  public matchGT($$dpth: number, $$cr?: ErrorTracker): Nullable<GT> {
    return this.regexAccept(String.raw`(?:>)`, "", $$dpth + 1, $$cr);
  }
  public matchLE($$dpth: number, $$cr?: ErrorTracker): Nullable<LE> {
    return this.regexAccept(String.raw`(?:<=)`, "", $$dpth + 1, $$cr);
  }
  public matchGE($$dpth: number, $$cr?: ErrorTracker): Nullable<GE> {
    return this.regexAccept(String.raw`(?:>=)`, "", $$dpth + 1, $$cr);
  }
  public matchPLUS($$dpth: number, $$cr?: ErrorTracker): Nullable<PLUS> {
    return this.regexAccept(String.raw`(?:\+)`, "", $$dpth + 1, $$cr);
  }
  public matchMINUS($$dpth: number, $$cr?: ErrorTracker): Nullable<MINUS> {
    return this.regexAccept(String.raw`(?:-)`, "", $$dpth + 1, $$cr);
  }
  public matchSTAR($$dpth: number, $$cr?: ErrorTracker): Nullable<STAR> {
    return this.regexAccept(String.raw`(?:\*)`, "", $$dpth + 1, $$cr);
  }
  public matchDIV($$dpth: number, $$cr?: ErrorTracker): Nullable<DIV> {
    return this.regexAccept(String.raw`(?:/)`, "", $$dpth + 1, $$cr);
  }
  public matchMOD($$dpth: number, $$cr?: ErrorTracker): Nullable<MOD> {
    return this.regexAccept(String.raw`(?:%)`, "", $$dpth + 1, $$cr);
  }
  public matchBITNOT($$dpth: number, $$cr?: ErrorTracker): Nullable<BITNOT> {
    return this.regexAccept(String.raw`(?:~)`, "", $$dpth + 1, $$cr);
  }
  public matchLNOT($$dpth: number, $$cr?: ErrorTracker): Nullable<LNOT> {
    return this.regexAccept(String.raw`(?:!)`, "", $$dpth + 1, $$cr);
  }
  public matchLPAREN($$dpth: number, $$cr?: ErrorTracker): Nullable<LPAREN> {
    return this.regexAccept(String.raw`(?:\()`, "", $$dpth + 1, $$cr);
  }
  public matchRPAREN($$dpth: number, $$cr?: ErrorTracker): Nullable<RPAREN> {
    return this.regexAccept(String.raw`(?:\))`, "", $$dpth + 1, $$cr);
  }
  public matchSTRING($$dpth: number, $$cr?: ErrorTracker): Nullable<STRING> {
    return this.run<STRING>($$dpth, () => {
      let $scope$str: Nullable<string>;
      let $$res: Nullable<STRING> = null;
      if (
        true &&
        this.regexAccept(String.raw`(?:\")`, "", $$dpth + 1, $$cr) !== null &&
        ($scope$str = this.regexAccept(
          String.raw`(?:([^\"\\]|\\.)*)`,
          "",
          $$dpth + 1,
          $$cr,
        )) !== null &&
        this.regexAccept(String.raw`(?:\")`, "", $$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.STRING, str: $scope$str };
      }
      return $$res;
    });
  }
  public matchIDENT($$dpth: number, $$cr?: ErrorTracker): Nullable<IDENT> {
    return this.regexAccept(
      String.raw`(?:@?[a-zA-Z_][a-zA-Z0-9_]*)`,
      "",
      $$dpth + 1,
      $$cr,
    );
  }
  public matchDECNUM($$dpth: number, $$cr?: ErrorTracker): Nullable<DECNUM> {
    return this.regexAccept(String.raw`(?:[0-9]+)`, "", $$dpth + 1, $$cr);
  }
  public matchHEXNUM($$dpth: number, $$cr?: ErrorTracker): Nullable<HEXNUM> {
    return this.regexAccept(
      String.raw`(?:(0x|\$)[0-9a-fA-F]+)`,
      "",
      $$dpth + 1,
      $$cr,
    );
  }
  public matchOCTNUM($$dpth: number, $$cr?: ErrorTracker): Nullable<OCTNUM> {
    return this.regexAccept(String.raw`(?:0o[0-7]+)`, "", $$dpth + 1, $$cr);
  }
  public matchBINNUM($$dpth: number, $$cr?: ErrorTracker): Nullable<BINNUM> {
    return this.regexAccept(String.raw`(?:0b[01]+)`, "", $$dpth + 1, $$cr);
  }
  public matchunimplemented(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<unimplemented> {
    return this.regexAccept(
      String.raw`(?:##################################)`,
      "",
      $$dpth + 1,
      $$cr,
    );
  }
  public test(): boolean {
    const mrk = this.mark();
    const res = this.matchline(0);
    const ans = res !== null;
    this.reset(mrk);
    return ans;
  }
  public parse(): ParseResult {
    const mrk = this.mark();
    const res = this.matchline(0);
    if (res) return { ast: res, errs: [] };
    this.reset(mrk);
    const rec = new ErrorTracker();
    this.clearMemos();
    this.matchline(0, rec);
    const err = rec.getErr();
    return { ast: res, errs: err !== null ? [err] : [] };
  }
  public mark(): PosInfo {
    return this.pos;
  }
  // @ts-ignore: loopPlus may not be called
  private loopPlus<T>(func: $$RuleType<T>): Nullable<[T, ...T[]]> {
    return this.loop(func, 1, -1) as Nullable<[T, ...T[]]>;
  }
  private loop<T>(func: $$RuleType<T>, lb: number, ub: number): Nullable<T[]> {
    const mrk = this.mark();
    const res: T[] = [];
    while (ub === -1 || res.length < ub) {
      const preMrk = this.mark();
      const t = func();
      if (t === null || this.pos.overallPos === preMrk.overallPos) {
        break;
      }
      res.push(t);
    }
    if (res.length >= lb) {
      return res;
    }
    this.reset(mrk);
    return null;
  }
  private run<T>($$dpth: number, fn: $$RuleType<T>): Nullable<T> {
    const mrk = this.mark();
    const res = fn();
    if (res !== null) return res;
    this.reset(mrk);
    return null;
  }
  // @ts-ignore: choice may not be called
  private choice<T>(fns: Array<$$RuleType<T>>): Nullable<T> {
    for (const f of fns) {
      const res = f();
      if (res !== null) {
        return res;
      }
    }
    return null;
  }
  private regexAccept(
    match: string,
    mods: string,
    dpth: number,
    cr?: ErrorTracker,
  ): Nullable<string> {
    return this.run<string>(dpth, () => {
      const reg = new RegExp(match, "y" + mods);
      const mrk = this.mark();
      reg.lastIndex = mrk.overallPos;
      const res = this.tryConsume(reg);
      if (cr) {
        cr.record(mrk, res, {
          kind: "RegexMatch",
          // We substring from 3 to len - 1 to strip off the
          // non-capture group syntax added as a WebKit workaround
          literal: match.substring(3, match.length - 1),
          negated: this.negating,
        });
      }
      return res;
    });
  }
  private tryConsume(reg: RegExp): Nullable<string> {
    const res = reg.exec(this.input);
    if (res) {
      let lineJmp = 0;
      let lind = -1;
      for (let i = 0; i < res[0].length; ++i) {
        if (res[0][i] === "\n") {
          ++lineJmp;
          lind = i;
        }
      }
      this.pos = {
        overallPos: reg.lastIndex,
        line: this.pos.line + lineJmp,
        offset:
          lind === -1
            ? this.pos.offset + res[0].length
            : res[0].length - lind - 1,
      };
      return res[0];
    }
    return null;
  }
  // @ts-ignore: noConsume may not be called
  private noConsume<T>(fn: $$RuleType<T>): Nullable<T> {
    const mrk = this.mark();
    const res = fn();
    this.reset(mrk);
    return res;
  }
  // @ts-ignore: negate may not be called
  private negate<T>(fn: $$RuleType<T>): Nullable<boolean> {
    const mrk = this.mark();
    const oneg = this.negating;
    this.negating = !oneg;
    const res = fn();
    this.negating = oneg;
    this.reset(mrk);
    return res === null ? true : null;
  }
  // @ts-ignore: Memoise may not be used
  private memoise<K>(
    rule: $$RuleType<K>,
    memo: Map<number, [Nullable<K>, PosInfo]>,
  ): Nullable<K> {
    const $scope$pos = this.mark();
    const $scope$memoRes = memo.get($scope$pos.overallPos);
    if (this.memoSafe && $scope$memoRes !== undefined) {
      this.reset($scope$memoRes[1]);
      return $scope$memoRes[0];
    }
    const $scope$result = rule();
    if (this.memoSafe)
      memo.set($scope$pos.overallPos, [$scope$result, this.mark()]);
    return $scope$result;
  }
  private match$EOF(et?: ErrorTracker): Nullable<{ kind: ASTKinds.$EOF }> {
    const res: { kind: ASTKinds.$EOF } | null = this.finished()
      ? { kind: ASTKinds.$EOF }
      : null;
    if (et)
      et.record(this.mark(), res, { kind: "EOF", negated: this.negating });
    return res;
  }
}
export function parse(s: string): ParseResult {
  const p = new Parser(s);
  return p.parse();
}
export interface ParseResult {
  ast: Nullable<line>;
  errs: SyntaxErr[];
}
export interface PosInfo {
  readonly overallPos: number;
  readonly line: number;
  readonly offset: number;
}
export interface RegexMatch {
  readonly kind: "RegexMatch";
  readonly negated: boolean;
  readonly literal: string;
}
export type EOFMatch = { kind: "EOF"; negated: boolean };
export type MatchAttempt = RegexMatch | EOFMatch;
export class SyntaxErr {
  public pos: PosInfo;
  public expmatches: MatchAttempt[];
  constructor(pos: PosInfo, expmatches: MatchAttempt[]) {
    this.pos = pos;
    this.expmatches = [...expmatches];
  }
  public toString(): string {
    return `Syntax Error at line ${this.pos.line}:${this.pos.offset}. Expected one of ${this.expmatches.map((x) => (x.kind === "EOF" ? " EOF" : ` ${x.negated ? "not " : ""}'${x.literal}'`))}`;
  }
}
class ErrorTracker {
  private mxpos: PosInfo = { overallPos: -1, line: -1, offset: -1 };
  private regexset: Set<string> = new Set();
  private pmatches: MatchAttempt[] = [];
  public record(pos: PosInfo, result: any, att: MatchAttempt): void {
    if ((result === null) === att.negated) return;
    if (pos.overallPos > this.mxpos.overallPos) {
      this.mxpos = pos;
      this.pmatches = [];
      this.regexset.clear();
    }
    if (this.mxpos.overallPos === pos.overallPos) {
      if (att.kind === "RegexMatch") {
        if (!this.regexset.has(att.literal)) this.pmatches.push(att);
        this.regexset.add(att.literal);
      } else {
        this.pmatches.push(att);
      }
    }
  }
  public getErr(): SyntaxErr | null {
    if (this.mxpos.overallPos !== -1)
      return new SyntaxErr(this.mxpos, this.pmatches);
    return null;
  }
}
